
const MAX_TOKEN_SIZE = 40;
const MIN_TOKEN_SIZE = 8;

const MAX_RADIUS = 400;
const MIN_RADIUS = 100;
const RADIUS_INCREMENT = 10;

const WINDOW_MAX = 100;

const TOKEN_CLASSNAME = "clockToken";
const ABILITY_CLASSNAME = "ability";

const EBS_URL = "http://localhost:3000";
const EBS_GRIMOIRE = "grimoire";
const EBS_CASTER = "broadcaster";

const SECRET_LENGTH = 32;


export default {
    MAX_TOKEN_SIZE,
    MIN_TOKEN_SIZE,
    MAX_RADIUS,
    MIN_RADIUS,
    RADIUS_INCREMENT,
    WINDOW_MAX,
    TOKEN_CLASSNAME,
    ABILITY_CLASSNAME,
    EBS_URL,
    EBS_GRIMOIRE,
    EBS_CASTER,
    SECRET_LENGTH
};

export { 
    MAX_TOKEN_SIZE,
    MIN_TOKEN_SIZE,
    MAX_RADIUS,
    MIN_RADIUS,
    RADIUS_INCREMENT,
    WINDOW_MAX,
    TOKEN_CLASSNAME,
    ABILITY_CLASSNAME,
    EBS_URL,
    EBS_GRIMOIRE,
    EBS_CASTER,
    SECRET_LENGTH
};